#include "code_generation.hpp"
#include <sstream>

namespace {
std::string defaultValue(ValueType type) {
    switch (type) {
        case ValueType::FLOAT: return "0.0";
        case ValueType::STRING: return "\"\"";
        case ValueType::BOOL: return "False";
        default: return "0";
    }
}
std::string pythonInput(ValueType type) {
    if (type == ValueType::INT) return "int(input())";
    if (type == ValueType::FLOAT) return "float(input())";
    if (type == ValueType::BOOL) return "(input().strip().lower() in ('hasa', 'true', '1'))";
    return "input()";
}
std::string pyOperator(const std::string& op) {
    if (op == "&&") return "and";
    if (op == "||") return "or";
    return op;
}
}

std::string CodeGenerator::expression(const Expr* e) const {
    if (!e) return "None";
    switch (e->kind) {
        case ExprKind::NUMBER: return e->text;
        case ExprKind::STRING_LITERAL: return e->text;
        case ExprKind::BOOLEAN: return e->text;
        case ExprKind::VARIABLE: return e->text;
        case ExprKind::INPUT: return "input()";
        case ExprKind::TYPE_NAME: return "\"" + e->text + "\"";
        case ExprKind::INDEX:
            usesIndexing_ = true;
            return "_cg_charat(" + expression(e->left) + ", " + expression(e->right) + ")";
        case ExprKind::UNARY:
            if (e->text == "!") return "(not " + expression(e->left) + ")";
            return "(" + e->text + expression(e->left) + ")";
        case ExprKind::BINARY: {
            std::string left = expression(e->left), right = expression(e->right);
            if (e->text == "+" && e->type == ValueType::STRING) {
                if (e->left->type != ValueType::STRING) left = "str(" + left + ")";
                if (e->right->type != ValueType::STRING) right = "str(" + right + ")";
            }
            return "(" + left + " " + pyOperator(e->text) + " " + right + ")";
        }
    }
    return "None";
}

void CodeGenerator::emit(const std::string& line, std::vector<std::string>& out) const {
    out.emplace_back(static_cast<std::size_t>(indent_) * 4, ' ');
    out.back() += line;
}

void CodeGenerator::statements(const std::vector<Stmt*>& list, std::vector<std::string>& out) const {
    for (const Stmt* s : list) {
        if (!s) continue;
        switch (s->kind) {
            case StmtKind::DECLARATION:
                emit(s->name + " = " + (s->expr ? (s->expr->kind == ExprKind::INPUT ? pythonInput(s->declaredType) : expression(s->expr)) : defaultValue(s->declaredType)), out);
                break;
            case StmtKind::ASSIGNMENT: {
                std::string rhs = s->expr && s->expr->kind == ExprKind::INPUT ? pythonInput(s->declaredType) : expression(s->expr);
                emit(s->name + " = " + rhs, out);
                break;
            }
            case StmtKind::INCREMENT: emit(s->name + (s->op == "++" ? " += 1" : " -= 1"), out); break;
            case StmtKind::PRINT: emit("print(" + expression(s->expr) + ")", out); break;
            case StmtKind::IF:
                emit("if " + expression(s->expr) + ":", out);
                ++indent_;
                if (s->body.empty()) emit("pass", out); else statements(s->body, out);
                --indent_;
                if (!s->elseBody.empty()) {
                    emit("else:", out); ++indent_; statements(s->elseBody, out); --indent_;
                }
                break;
            case StmtKind::WHILE:
                emit("while " + expression(s->expr) + ":", out);
                ++indent_;
                if (s->body.empty()) emit("pass", out); else statements(s->body, out);
                --indent_;
                break;
            case StmtKind::BREAK: emit("break", out); break;
            case StmtKind::CONTINUE: emit("continue", out); break;
            case StmtKind::BLOCK: if (s->body.empty()) emit("pass", out); else statements(s->body, out); break;
            case StmtKind::INCLUDE: break;
        }
    }
}

std::string CodeGenerator::generate(const std::vector<Stmt*>& program) const {
    indent_ = 0;
    usesIndexing_ = false;
    std::vector<std::string> body;
    statements(program, body);
    std::ostringstream out;
    out << "#!/usr/bin/env python3\n# Generated by Chatgaiya++ Flex/recursive-descent compiler\n\n";
    if (usesIndexing_) out << "def _cg_charat(s, i):\n    try:\n        return s[i]\n    except (IndexError, TypeError):\n        return \"\"\n\n";
    if (body.empty()) body.push_back("pass");
    for (const auto& line : body) out << line << '\n';
    return out.str();
}
