#!/usr/bin/env python3
# Generated by Chatgaiya++ Flex/recursive-descent compiler

def _cg_charat(s, i):
    try:
        return s[i]
    except (IndexError, TypeError):
        return ""

word = "Chatgaiya"
i = 0
while (i < 3):
    print(_cg_charat(word, i))
    i += 1
good = True
if good:
    print("ok")
else:
    print("bad")
