#!/usr/bin/env python3
# Generated by Chatgaiya++ Flex/recursive-descent compiler

ok = True
i = 1
while ok:
    if (i > 5):
        ok = False
    else:
        if ((i % 2) == 0):
            print("Zur Songkha")
        else:
            print("BiZur Songkha")
    i += 1
print("ongko")
